org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version_range=[1.21.1,1.22)
minecraft_version=1.21.1
loader_version=0.17.2
fabric_version=0.116.6+1.21.1
# The Minecraft version the Parchment version is for
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_id=superbwarfare
mod_name=Superb Warfare ReFabricated
mod_license=GNU General Public License v3.0
mod_description=A Warfare Mod
mod_version=0.8.9.1
mod_authors=Atsuishio, Roki27, Light_Quanta, CrawKatt
# dependencies
jei_version=19.21.0.247
cloth_config_version=11.1.106
jade_version=4681833
real_camera_id=6943480
trinkets_version=3.10.0
extensibleenums_version=21.1.1
cardinal_components_version=6.1.3
fabric_kotlin_version=1.13.2+kotlin.2.1.20
simple_bedrock_model_version=23b1a23f99fe274ec49f59718424ad94386b6570
ponder_version=1.0.69
sable_companion_version=1.6.0
