package com.atsuishio.superbwarfare.network;

import com.atsuishio.superbwarfare.network.message.receive.ClientIndicatorMessage;
import com.atsuishio.superbwarfare.network.message.receive.ClientMotionSyncMessage;
import com.atsuishio.superbwarfare.network.message.receive.ClientSetMotionMessage;
import com.atsuishio.superbwarfare.network.message.receive.ClientTacticalSprintSyncMessage;
import com.atsuishio.superbwarfare.network.message.receive.ContainerDataMessage;
import com.atsuishio.superbwarfare.network.message.receive.DataSyncMessage;
import com.atsuishio.superbwarfare.network.message.receive.DrawClientMessage;
import com.atsuishio.superbwarfare.network.message.receive.FinishAssemblingVehicleMessage;
import com.atsuishio.superbwarfare.network.message.receive.GunsDataMessage;
import com.atsuishio.superbwarfare.network.message.receive.LivingGunKillMessage;
import com.atsuishio.superbwarfare.network.message.receive.RadarMenuCloseMessage;
import com.atsuishio.superbwarfare.network.message.receive.RadarMenuOpenMessage;
import com.atsuishio.superbwarfare.network.message.receive.ResetCameraTypeMessage;
import com.atsuishio.superbwarfare.network.message.receive.ShakeClientMessage;
import com.atsuishio.superbwarfare.network.message.receive.ShootClientMessage;
import com.atsuishio.superbwarfare.network.message.receive.SoundClientMessage;
import com.atsuishio.superbwarfare.network.message.receive.TDMSyncMessage;
import com.atsuishio.superbwarfare.network.message.receive.VehiclesDataMessage;
import com.atsuishio.superbwarfare.network.message.send.*;
import net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking;
import net.fabricmc.fabric.api.networking.v1.PayloadTypeRegistry;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;

public class NetworkRegistry {

    public static void registerPayloads() {
        PayloadTypeRegistry.playS2C().register(ShakeClientMessage.TYPE, ShakeClientMessage.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(ClientMotionSyncMessage.TYPE, ClientMotionSyncMessage.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(ClientIndicatorMessage.TYPE, ClientIndicatorMessage.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(LivingGunKillMessage.TYPE, LivingGunKillMessage.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(GunsDataMessage.TYPE, GunsDataMessage.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(ContainerDataMessage.TYPE, ContainerDataMessage.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(ShootClientMessage.TYPE, ShootClientMessage.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(DrawClientMessage.TYPE, DrawClientMessage.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(ResetCameraTypeMessage.TYPE, ResetCameraTypeMessage.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(RadarMenuOpenMessage.TYPE, RadarMenuOpenMessage.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(RadarMenuCloseMessage.TYPE, RadarMenuCloseMessage.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(ClientTacticalSprintSyncMessage.TYPE, ClientTacticalSprintSyncMessage.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(VehiclesDataMessage.TYPE, VehiclesDataMessage.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(ClientSetMotionMessage.TYPE, ClientSetMotionMessage.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(FinishAssemblingVehicleMessage.TYPE, FinishAssemblingVehicleMessage.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(TDMSyncMessage.TYPE, TDMSyncMessage.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(SoundClientMessage.TYPE, SoundClientMessage.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(DataSyncMessage.TYPE, DataSyncMessage.STREAM_CODEC);

        PayloadTypeRegistry.playC2S().register(LaserShootMessage.TYPE, LaserShootMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(ShootMessage.TYPE, ShootMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(DoubleJumpMessage.TYPE, DoubleJumpMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(ParachuteMessage.TYPE, ParachuteMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(VehicleMovementMessage.TYPE, VehicleMovementMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(MeleeAttackMessage.TYPE, MeleeAttackMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(LungeMineAttackMessage.TYPE, LungeMineAttackMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(VehicleFireMessage.TYPE, VehicleFireMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(AimVillagerMessage.TYPE, AimVillagerMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RadarChangeModeMessage.TYPE, RadarChangeModeMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RadarSetParametersMessage.TYPE, RadarSetParametersMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RadarSetPosMessage.TYPE, RadarSetPosMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RadarSetTargetMessage.TYPE, RadarSetTargetMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(GunReforgeMessage.TYPE, GunReforgeMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(SetPerkLevelMessage.TYPE, SetPerkLevelMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(SwitchVehicleWeaponMessage.TYPE, SwitchVehicleWeaponMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(AdjustZoomFovMessage.TYPE, AdjustZoomFovMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(SwitchScopeMessage.TYPE, SwitchScopeMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(FireKeyMessage.TYPE, FireKeyMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(ReloadMessage.TYPE, ReloadMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(FireModeMessage.TYPE, FireModeMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(PlayerStopRidingMessage.TYPE, PlayerStopRidingMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(ZoomMessage.TYPE, ZoomMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(DroneFireMessage.TYPE, DroneFireMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(SetFiringParametersMessage.TYPE, SetFiringParametersMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(ArtilleryIndicatorFireMessage.TYPE, ArtilleryIndicatorFireMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(SensitivityMessage.TYPE, SensitivityMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(EditMessage.TYPE, EditMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(InteractMessage.TYPE, InteractMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(AdjustMortarAngleMessage.TYPE, AdjustMortarAngleMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(ChangeVehicleSeatMessage.TYPE, ChangeVehicleSeatMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(ShowChargingRangeMessage.TYPE, ShowChargingRangeMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(TacticalSprintMessage.TYPE, TacticalSprintMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(DogTagFinishEditMessage.TYPE, DogTagFinishEditMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(MouseMoveMessage.TYPE, MouseMoveMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(FiringParametersEditMessage.TYPE, FiringParametersEditMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(UnloadMessage.TYPE, UnloadMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(AssembleVehicleMessage.TYPE, AssembleVehicleMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(SeekingWeaponWarningMessage.TYPE, SeekingWeaponWarningMessage.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(WeaponZoomingMessage.TYPE, WeaponZoomingMessage.STREAM_CODEC);

        ServerPlayNetworking.registerGlobalReceiver(LaserShootMessage.TYPE, LaserShootMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(ShootMessage.TYPE, ShootMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(DoubleJumpMessage.TYPE, (message, context) -> DoubleJumpMessage.handler(context));
        ServerPlayNetworking.registerGlobalReceiver(ParachuteMessage.TYPE, (msg, ctx) -> ParachuteMessage.handler(ctx));
        ServerPlayNetworking.registerGlobalReceiver(VehicleMovementMessage.TYPE, VehicleMovementMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(MeleeAttackMessage.TYPE, MeleeAttackMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(LungeMineAttackMessage.TYPE, LungeMineAttackMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(VehicleFireMessage.TYPE, VehicleFireMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(AimVillagerMessage.TYPE, AimVillagerMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(RadarChangeModeMessage.TYPE, RadarChangeModeMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(RadarSetParametersMessage.TYPE, RadarSetParametersMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(RadarSetPosMessage.TYPE, RadarSetPosMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(RadarSetTargetMessage.TYPE, RadarSetTargetMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(GunReforgeMessage.TYPE, (message1, context1) -> GunReforgeMessage.handler(context1));
        ServerPlayNetworking.registerGlobalReceiver(SetPerkLevelMessage.TYPE, SetPerkLevelMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(SwitchVehicleWeaponMessage.TYPE, SwitchVehicleWeaponMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(AdjustZoomFovMessage.TYPE, AdjustZoomFovMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(SwitchScopeMessage.TYPE, SwitchScopeMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(FireKeyMessage.TYPE, FireKeyMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(ReloadMessage.TYPE, (message2, context2) -> ReloadMessage.handler(context2));
        ServerPlayNetworking.registerGlobalReceiver(FireModeMessage.TYPE, FireModeMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(PlayerStopRidingMessage.TYPE, PlayerStopRidingMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(ZoomMessage.TYPE, ZoomMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(DroneFireMessage.TYPE, DroneFireMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(SetFiringParametersMessage.TYPE, (message, context) -> SetFiringParametersMessage.handler(context));
        ServerPlayNetworking.registerGlobalReceiver(ArtilleryIndicatorFireMessage.TYPE, (message, context) -> ArtilleryIndicatorFireMessage.handler(context));
        ServerPlayNetworking.registerGlobalReceiver(SensitivityMessage.TYPE, SensitivityMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(EditMessage.TYPE, EditMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(InteractMessage.TYPE, (interactMessage, context) -> InteractMessage.handler(context));
        ServerPlayNetworking.registerGlobalReceiver(AdjustMortarAngleMessage.TYPE, AdjustMortarAngleMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(ChangeVehicleSeatMessage.TYPE, ChangeVehicleSeatMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(ShowChargingRangeMessage.TYPE, ShowChargingRangeMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(TacticalSprintMessage.TYPE, TacticalSprintMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(DogTagFinishEditMessage.TYPE, DogTagFinishEditMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(MouseMoveMessage.TYPE, MouseMoveMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(FiringParametersEditMessage.TYPE, FiringParametersEditMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(UnloadMessage.TYPE, (msg, ctx) -> UnloadMessage.handler(ctx));
        ServerPlayNetworking.registerGlobalReceiver(AssembleVehicleMessage.TYPE, AssembleVehicleMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(SeekingWeaponWarningMessage.TYPE, SeekingWeaponWarningMessage::handler);
        ServerPlayNetworking.registerGlobalReceiver(WeaponZoomingMessage.TYPE, WeaponZoomingMessage::handler);
    }

    public static void registerClientReceivers() {
        ClientPlayNetworking.registerGlobalReceiver(ShakeClientMessage.TYPE, (msg, ctx) -> ShakeClientMessage.handler(msg));
        ClientPlayNetworking.registerGlobalReceiver(ClientMotionSyncMessage.TYPE, (msg, ctx) -> ClientMotionSyncMessage.handler(msg));
        ClientPlayNetworking.registerGlobalReceiver(ClientIndicatorMessage.TYPE, (msg, ctx) -> ClientIndicatorMessage.handler(msg));
        ClientPlayNetworking.registerGlobalReceiver(LivingGunKillMessage.TYPE, (msg, ctx) -> LivingGunKillMessage.handler(msg));
        ClientPlayNetworking.registerGlobalReceiver(GunsDataMessage.TYPE, (msg, ctx) -> GunsDataMessage.handler(msg));
        ClientPlayNetworking.registerGlobalReceiver(ContainerDataMessage.TYPE, (msg, ctx) -> ContainerDataMessage.handler(msg));
        ClientPlayNetworking.registerGlobalReceiver(ShootClientMessage.TYPE, (msg, ctx) -> ShootClientMessage.handler(msg));
        ClientPlayNetworking.registerGlobalReceiver(DrawClientMessage.TYPE, (msg, ctx) -> DrawClientMessage.handler());
        ClientPlayNetworking.registerGlobalReceiver(ResetCameraTypeMessage.TYPE, (message2, context2) -> ResetCameraTypeMessage.handler());
        ClientPlayNetworking.registerGlobalReceiver(RadarMenuOpenMessage.TYPE, (msg, ctx) -> RadarMenuOpenMessage.handler(msg));
        ClientPlayNetworking.registerGlobalReceiver(RadarMenuCloseMessage.TYPE, (message1, context1) -> RadarMenuCloseMessage.handler());
        ClientPlayNetworking.registerGlobalReceiver(ClientTacticalSprintSyncMessage.TYPE, (msg, ctx) -> ClientTacticalSprintSyncMessage.handler(msg));
        ClientPlayNetworking.registerGlobalReceiver(VehiclesDataMessage.TYPE, (msg, ctx) -> VehiclesDataMessage.handler(msg));
        ClientPlayNetworking.registerGlobalReceiver(ClientSetMotionMessage.TYPE, (msg, ctx) -> ClientSetMotionMessage.handler(msg));
        ClientPlayNetworking.registerGlobalReceiver(FinishAssemblingVehicleMessage.TYPE, (message3, context3) -> FinishAssemblingVehicleMessage.handler(message3));
        ClientPlayNetworking.registerGlobalReceiver(TDMSyncMessage.TYPE, (message3, context3) -> TDMSyncMessage.handler(message3));
        ClientPlayNetworking.registerGlobalReceiver(SoundClientMessage.TYPE, (message3, context3) -> SoundClientMessage.handler(message3));
        ClientPlayNetworking.registerGlobalReceiver(DataSyncMessage.TYPE, (message, context) -> DataSyncMessage.handler(message));
    }
}
