// Auto-generated by The Ponderer — do not edit; will be overwritten on next export.
// 由思索者自动生成 — 请勿手动修改；下次导出时会被覆盖。
package com.atsuishio.superbwarfare.compat.ponder.scene;

import com.atsuishio.superbwarfare.compat.ponder.GeneratedPonderSupport;
import net.createmod.ponder.api.registration.PonderSceneRegistrationHelper;
import net.createmod.ponder.api.registration.PonderTagRegistrationHelper;
import net.createmod.ponder.api.scene.SceneBuilder;
import net.createmod.ponder.api.scene.SceneBuildingUtil;
import net.minecraft.core.BlockPos;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.phys.Vec3;

import java.util.Map;

public final class GeneratedBiogasGenerator_e0223ac6 {
    private GeneratedBiogasGenerator_e0223ac6() {
    }

    public static void register(PonderSceneRegistrationHelper<ResourceLocation> helper) {
        ResourceLocation[] tags = new ResourceLocation[]{ResourceLocation.fromNamespaceAndPath("superbwarfare", "ponderer_exported")};
        var multi = helper.forComponents(java.util.List.of(ResourceLocation.fromNamespaceAndPath("superbwarfare", "biogas_generator")));
        multi.addStoryBoard(ResourceLocation.fromNamespaceAndPath("superbwarfare", "generated/ponderer/basic_l"), GeneratedBiogasGenerator_e0223ac6::storyboard$0, tags);
    }

    public static void registerTags(PonderTagRegistrationHelper<ResourceLocation> helper) {
        ResourceLocation tag = GeneratedPonderAttribution.tag();
        helper.addTagToComponent(ResourceLocation.fromNamespaceAndPath("superbwarfare", "biogas_generator"), tag);
    }

    private static void storyboard$0(SceneBuilder scene, SceneBuildingUtil util) {
        scene.title("biogas_generator", "Scene 1");
        GeneratedPonderSupport.Context context = new GeneratedPonderSupport.Context();
        GeneratedPonderSupport.preScanBounds(scene, new BlockPos(1, 1, 3), new BlockPos(3, 2, 4));
        scene.addKeyframe();
        GeneratedPonderSupport.showStructure(scene, context, null, null, null, null);
        scene.idle(20);
        GeneratedPonderSupport.setBlock(scene, context, "superbwarfare:biogas_generator", null, new BlockPos(3, 1, 3), null, "{Power:0.0f}", false, false, "down", 20, 1, false, null, "down");
        scene.idle(20);
        scene.addKeyframe();
        GeneratedPonderSupport.showText(scene, "这是一种十分有味道的发电设施", new Vec3(3.5, 1.0, 3.5), 60, null, true);
        scene.idle(80);
        GeneratedPonderSupport.setBlock(scene, context, "minecraft:composter", Map.ofEntries(Map.entry("level", "0")), new BlockPos(3, 2, 3), null, null, false, false, "down", 20, 1, false, null, "down");
        scene.addKeyframe();
        GeneratedPonderSupport.showText(scene, "检测其上方放置的堆肥桶内部特定生物数量，数量越多，发电效率越高", new Vec3(3.5, 1.0, 3.5), 60, null, true);
        scene.idle(80);
        GeneratedPonderSupport.setBlock(scene, context, "superbwarfare:charging_station", Map.ofEntries(Map.entry("show_range", "false"), Map.entry("facing", "south")), new BlockPos(3, 1, 4), null, "{Energy:0,FuelTick:0,Items:[],MaxFuelTick:1600,ShowRange:0b}", false, false, "down", 20, 1, false, null, "down");
        GeneratedPonderSupport.setBlock(scene, context, "minecraft:comparator", Map.ofEntries(Map.entry("mode", "compare"), Map.entry("facing", "east")), new BlockPos(2, 1, 4), null, "{OutputSignal:11}", false, false, "down", 20, 1, false, null, "down");
        GeneratedPonderSupport.setBlock(scene, context, "minecraft:redstone_lamp", null, new BlockPos(1, 1, 4), null, null, false, false, "down", 20, 1, false, null, "down");
        scene.addKeyframe();
        GeneratedPonderSupport.showText(scene, "这是最简单的检测方式", new Vec3(2.0, 1.5, 4.5), 60, null, true);
        scene.idle(80);
        GeneratedPonderSupport.createEntity(scene, context, "superbwarfare:senpai", new Vec3(3.5, 2.0, 3.5), null, null, null, "{AbsorptionAmount:0.0f,ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],ArmorItems:[{},{},{},{}],Attributes:[{Base:0.08d,Name:\"forge:entity_gravity\"},{Base:0.0d,Name:\"forge:step_height_addition\"},{Base:0.23d,Name:\"minecraft:generic.movement_speed\"}],Brain:{memories:{}},CanPickUpLoot:0b,CanUpdate:1b,FallFlying:0b,ForgeCaps:{\"curios:inventory\":{Curios:[]},\"superbwarfare:phosphorus_fire_capability\":{SbwPhosphorusFire:0b}},ForgeData:{},HandDropChances:[0.085f,0.085f],HandItems:[{},{}],Health:24.0f,HurtByTimestamp:0,Invulnerable:0b,LeftHanded:1b,PersistenceRequired:0b,Runner:0b}", null, "simultaneous", null, "down");
        scene.addKeyframe();
        GeneratedPonderSupport.showText(scene, "放置生物即可发电", new Vec3(3.5, 2.0, 3.5), 60, null, true);
        GeneratedPonderSupport.modifyBlockEntity(scene, Map.ofEntries(Map.entry("show_range", "false")), "{Energy:3998572,FuelTick:0,Items:[],MaxFuelTick:1600,ShowRange:0b}", true, new BlockPos(3, 1, 4), null);
        GeneratedPonderSupport.modifyBlockEntity(scene, Map.ofEntries(Map.entry("mode", "compare"), Map.entry("powered", "true"), Map.entry("facing", "east")), "{OutputSignal:14}", true, new BlockPos(2, 1, 4), null);
        GeneratedPonderSupport.modifyBlockEntity(scene, Map.ofEntries(Map.entry("lit", "true")), null, true, new BlockPos(1, 1, 4), null);
        scene.idle(80);
    }

}
