// Auto-generated by The Ponderer — do not edit; will be overwritten on next export.
// 由思索者自动生成 — 请勿手动修改；下次导出时会被覆盖。
package com.atsuishio.superbwarfare.compat.ponder.scene;

import com.atsuishio.superbwarfare.compat.ponder.GeneratedPonderSupport;
import net.createmod.ponder.api.registration.PonderSceneRegistrationHelper;
import net.createmod.ponder.api.registration.PonderTagRegistrationHelper;
import net.createmod.ponder.api.scene.SceneBuilder;
import net.createmod.ponder.api.scene.SceneBuildingUtil;
import net.minecraft.core.BlockPos;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.phys.Vec3;

public final class GeneratedVehicleAssemblingTable_253a6d6f {
    private GeneratedVehicleAssemblingTable_253a6d6f() {
    }

    public static void register(PonderSceneRegistrationHelper<ResourceLocation> helper) {
        ResourceLocation[] tags = new ResourceLocation[]{ResourceLocation.fromNamespaceAndPath("superbwarfare", "ponderer_exported")};
        var multi = helper.forComponents(java.util.List.of(ResourceLocation.fromNamespaceAndPath("superbwarfare", "vehicle_assembling_table")));
        multi.addStoryBoard(ResourceLocation.fromNamespaceAndPath("superbwarfare", "generated/ponderer/basic_l"), GeneratedVehicleAssemblingTable_253a6d6f::storyboard$0, tags);
        multi.addStoryBoard(ResourceLocation.fromNamespaceAndPath("superbwarfare", "generated/ponderer/basic_l"), GeneratedVehicleAssemblingTable_253a6d6f::storyboard$1, tags);
    }

    public static void registerTags(PonderTagRegistrationHelper<ResourceLocation> helper) {
        ResourceLocation tag = GeneratedPonderAttribution.tag();
        helper.addTagToComponent(ResourceLocation.fromNamespaceAndPath("superbwarfare", "vehicle_assembling_table"), tag);
    }

    private static void storyboard$0(SceneBuilder scene, SceneBuildingUtil util) {
        scene.title("vehicle_assembling_table_scene_1", "Scene 1");
        GeneratedPonderSupport.Context context = new GeneratedPonderSupport.Context();
        GeneratedPonderSupport.preScanBounds(scene, new BlockPos(3, 1, 3), new BlockPos(3, 1, 3));
        scene.addKeyframe();
        GeneratedPonderSupport.showStructure(scene, context, null, null, null, null);
        GeneratedPonderSupport.setBlock(scene, context, "superbwarfare:vehicle_assembling_table", null, new BlockPos(3, 1, 3), null, null, false, false, "none", null, null, null, null, null);
        scene.idle(20);
        scene.addKeyframe();
        GeneratedPonderSupport.showText(scene, "Edit this ponder scene!", new Vec3(2.5, 2.0, 2.5), 40, null, true);
        scene.idle(60);
        scene.addKeyframe();
        GeneratedPonderSupport.showText(scene, "右击可以打开装配界面", new Vec3(3.5, 2.0, 3.5), 40, null, true);
        scene.idle(20);
        GeneratedPonderSupport.showControls(scene, new Vec3(3.5, 2.0, 3.5), "right", 20, "right", null, null, false, false);
        scene.idle(60);
        scene.addKeyframe();
        GeneratedPonderSupport.showText(scene, "只要背包中有足够的材料，就可以直接合成物品", new Vec3(3.5, 2.0, 3.5), 60, null, true);
        scene.idle(60);
    }

    private static void storyboard$1(SceneBuilder scene, SceneBuildingUtil util) {
        scene.title("vehicle_assembling_table_s_df2b0", "交互?");
        GeneratedPonderSupport.Context context = new GeneratedPonderSupport.Context();
        GeneratedPonderSupport.preScanBounds(scene, new BlockPos(2, 1, 3), new BlockPos(3, 2, 4));
        GeneratedPonderSupport.showStructure(scene, context, null, null, null, null);
        GeneratedPonderSupport.setBlock(scene, context, "superbwarfare:vehicle_assembling_table", null, new BlockPos(3, 1, 3), null, null, false, false, "none", null, null, null, null, null);
        scene.idle(20);
        GeneratedPonderSupport.showText(scene, "使用撬棍右击的话……", new Vec3(3.5, 2.0, 3.5), 40, null, true);
        scene.idle(20);
        GeneratedPonderSupport.showControls(scene, new Vec3(3.5, 2.0, 3.5), "right", 40, "right", "superbwarfare:crowbar", null, false, false);
        scene.idle(20);
        GeneratedPonderSupport.destroyBlock(scene, context, new BlockPos(3, 1, 3), new BlockPos(2, 2, 4), null);
        GeneratedPonderSupport.createEntity(scene, context, "superbwarfare:vehicle_assembling_table", new Vec3(3.0, 1.1, 4.0), null, null, null, null, "1", null, null, null);
        scene.idle(20);
    }

}
