// Auto-generated by The Ponderer — do not edit; will be overwritten on next export.
// 由思索者自动生成 — 请勿手动修改；下次导出时会被覆盖。
package com.atsuishio.superbwarfare.compat.ponder.scene;

import com.atsuishio.superbwarfare.compat.ponder.GeneratedPonderSupport;
import net.createmod.ponder.api.registration.PonderSceneRegistrationHelper;
import net.createmod.ponder.api.registration.PonderTagRegistrationHelper;
import net.createmod.ponder.api.scene.SceneBuilder;
import net.createmod.ponder.api.scene.SceneBuildingUtil;
import net.minecraft.core.BlockPos;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.phys.Vec3;

import java.util.Map;

public final class GeneratedReforgingTable_4f93e636 {
    private GeneratedReforgingTable_4f93e636() {
    }

    public static void register(PonderSceneRegistrationHelper<ResourceLocation> helper) {
        ResourceLocation[] tags = new ResourceLocation[]{ResourceLocation.fromNamespaceAndPath("superbwarfare", "ponderer_exported")};
        var multi = helper.forComponents(java.util.List.of(ResourceLocation.fromNamespaceAndPath("superbwarfare", "reforging_table")));
        multi.addStoryBoard(ResourceLocation.fromNamespaceAndPath("superbwarfare", "generated/ponderer/basic"), GeneratedReforgingTable_4f93e636::storyboard$0, tags);
        multi.addStoryBoard(ResourceLocation.fromNamespaceAndPath("superbwarfare", "generated/ponderer/basic"), GeneratedReforgingTable_4f93e636::storyboard$1, tags);
    }

    public static void registerTags(PonderTagRegistrationHelper<ResourceLocation> helper) {
        ResourceLocation tag = GeneratedPonderAttribution.tag();
        helper.addTagToComponent(ResourceLocation.fromNamespaceAndPath("superbwarfare", "reforging_table"), tag);
    }

    private static void storyboard$0(SceneBuilder scene, SceneBuildingUtil util) {
        scene.title("reforging_table_scene_1", "Scene 1");
        GeneratedPonderSupport.Context context = new GeneratedPonderSupport.Context();
        GeneratedPonderSupport.preScanBounds(scene, new BlockPos(2, 1, 2), new BlockPos(2, 1, 2));
        scene.addKeyframe();
        GeneratedPonderSupport.showStructure(scene, context, null, null, null, null);
        scene.idle(20);
        GeneratedPonderSupport.setBlock(scene, context, "superbwarfare:reforging_table", Map.ofEntries(Map.entry("waterlogged", "false"), Map.entry("facing", "south")), new BlockPos(2, 1, 2), null, null, false, false, "down", 20, 1, false, null, "down");
        scene.idle(20);
        scene.addKeyframe();
        GeneratedPonderSupport.showText(scene, "枪械重铸台是一种可以强化枪械的工作方块", new Vec3(2.5, 1.0, 2.5), 60, null, true);
        scene.idle(80);
    }
}
