package com.atsuishio.superbwarfare.init

import com.atsuishio.superbwarfare.client.renderer.entity.*
import com.atsuishio.superbwarfare.client.renderer.projectile.*
import net.fabricmc.fabric.api.client.rendering.v1.EntityRendererRegistry

object ModEntityRenderers {

    @JvmStatic
    fun init() {
        EntityRendererRegistry.register(ModEntities.MORTAR, ::MortarRenderer)
        EntityRendererRegistry.register(ModEntities.SENPAI, ::SenpaiRenderer)
        EntityRendererRegistry.register(ModEntities.CLAYMORE, ::ClaymoreRenderer)
        EntityRendererRegistry.register(ModEntities.C4, ::C4Renderer)
        EntityRendererRegistry.register(ModEntities.TASER_BULLET, ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.GUN_GRENADE, ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.TARGET, ::TargetRenderer)
        EntityRendererRegistry.register(ModEntities.DPS_GENERATOR, ::DPSGeneratorRenderer)
        EntityRendererRegistry.register(ModEntities.RPG_ROCKET_TBG, ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.RPG_ROCKET_STANDARD, ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.SMALL_ROCKET, ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.MEDIUM_ROCKET, ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.MORTAR_SHELL, ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.CANNON_SHELL, ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.PROJECTILE, ::ProjectileEntityRenderer)
        EntityRendererRegistry.register(ModEntities.MK_42, ::Mk42Renderer)
        EntityRendererRegistry.register(ModEntities.DRONE, ::DroneRenderer)
        EntityRendererRegistry.register(ModEntities.HAND_GRENADE, ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.RGO_GRENADE, ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.M18_SMOKE_GRENADE, ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.MLE_1934, ::Mle1934Renderer)
        EntityRendererRegistry.register(ModEntities.JAVELIN_MISSILE, ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.ANNIHILATOR, ::AnnihilatorRenderer)
        EntityRendererRegistry.register(ModEntities.SPEEDBOAT, ::SpeedboatRenderer)
        EntityRendererRegistry.register(ModEntities.TINY_SPEEDBOAT, ::TinySpeedboatRenderer)
        EntityRendererRegistry.register(ModEntities.WHEEL_CHAIR, ::WheelChairRenderer)
        EntityRendererRegistry.register(ModEntities.AH_6, ::Ah6Renderer)
        EntityRendererRegistry.register(ModEntities.FLARE_DECOY, ::FlareDecoyEntityRenderer)
        EntityRendererRegistry.register(
            ModEntities.WHITE_PHOSPHORUS_PROJECTILE,
            ::WhitePhosphorusProjectileEntityRenderer
        )
        EntityRendererRegistry.register(ModEntities.PRISMATIC_BOLT, ::PrismaticBoltEntityRenderer)
        EntityRendererRegistry.register(ModEntities.SMOKE_DECOY, ::SmokeDecoyEntityRenderer)
        EntityRendererRegistry.register(ModEntities.LAV_150, ::Lav150Renderer)
        EntityRendererRegistry.register(ModEntities.SMALL_CANNON_SHELL, ::SmallCannonShellEntityRenderer)
        EntityRendererRegistry.register(ModEntities.TOM_6, ::Tom6Renderer)
        EntityRendererRegistry.register(ModEntities.MELON_BOMB, ::MelonBombEntityRenderer)
        EntityRendererRegistry.register(ModEntities.BMP_2, ::Bmp2Renderer)
        EntityRendererRegistry.register(ModEntities.WIRE_GUIDE_MISSILE, ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.LASER_TOWER, ::LaserTowerRenderer)
        EntityRendererRegistry.register(ModEntities.YX_100, ::Yx100Renderer)
        EntityRendererRegistry.register(ModEntities.PRISM_TANK, ::PrismTankRenderer)
        EntityRendererRegistry.register(ModEntities.SWARM_DRONE, ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.HPJ_11, ::Hpj11Renderer)
        EntityRendererRegistry.register(ModEntities.A_10A, ::A10Renderer)
        EntityRendererRegistry.register(ModEntities.MK_82, ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.SC_50, ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.SC_250, ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.AGM_65, ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.BLU_43, ::Blu43Renderer)
        EntityRendererRegistry.register(ModEntities.TM_62, ::Tm62Renderer)
        EntityRendererRegistry.register(ModEntities.PTKM_1R, ::Ptkm1rRenderer)
        EntityRendererRegistry.register(ModEntities.PTKM_PROJECTILE, ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.TYPE_63, ::Type63Renderer)
        EntityRendererRegistry.register(ModEntities.MEDICAL_KIT, ::MedicalKitEntityRenderer)
        EntityRendererRegistry.register(ModEntities.BL_132, ::Bl132Renderer)
        EntityRendererRegistry.register(ModEntities.GRAPESHOT, ::GrapeshotRenderer)
        EntityRendererRegistry.register(ModEntities.SUPER_STAR_PROJECTILE, ::SuperStarProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.VEHICLE_ASSEMBLING_TABLE, ::VehicleAssemblingTableVehicleRenderer)
        EntityRendererRegistry.register(ModEntities.WAVEFORCE_TOWER, ::WaveforceTowerRenderer)
        EntityRendererRegistry.register(ModEntities.IGLA_MISSILE, ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.RU_9M336_MISSILE, ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.TRUCK, ::TruckRenderer)
        EntityRendererRegistry.register(ModEntities.SODAYO_PICK_UP, ::SodayoPickUpRenderer)
        EntityRendererRegistry.register(ModEntities.SODAYO_PICK_UP_HMG, ::SodayoPickUpHmgRenderer)
        EntityRendererRegistry.register(ModEntities.SODAYO_PICK_UP_ROCKET, ::SodayoPickUpRocketRenderer)
        EntityRendererRegistry.register(ModEntities.SODAYO_PICK_UP_TOW, ::SodayoPickUpTowRenderer)
        EntityRendererRegistry.register(ModEntities.TOW, ::TowRenderer)
        EntityRendererRegistry.register(ModEntities.STEEL_COIL, ::SteelCoilRenderer)
        EntityRendererRegistry.register(ModEntities.MI_28, ::Mi28Renderer)
        EntityRendererRegistry.register(ModEntities.KH_39, ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.PLZ_05, ::Plz05Renderer)
        EntityRendererRegistry.register(ModEntities.LAV_AD, ::LavAdRenderer)
        EntityRendererRegistry.register(ModEntities.KV_16, ::Kv16Renderer)
        EntityRendererRegistry.register(ModEntities.JU_87, ::Ju87Renderer)
        EntityRendererRegistry.register(ModEntities.T_90A, ::T90aRenderer)
        EntityRendererRegistry.register(ModEntities.M_1A_2, ::M1A2Renderer)
        EntityRendererRegistry.register(ModEntities.BRADLEY, ::BradleyRenderer)
        EntityRendererRegistry.register(ModEntities.TURRET_WRECK, ::TurretWreckRenderer)
        EntityRendererRegistry.register(ModEntities.LAV_25, ::Lav25Renderer)
        EntityRendererRegistry.register(ModEntities.ZTZ_99A, ::Ztz99aRenderer)
        EntityRendererRegistry.register(ModEntities.EDD, ::EDDRenderer)
    }
}